name: CI/CD Smart Docker Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        # 🎯 जादू यहाँ है: यह 'latest' के साथ-साथ एक नया नंबर (जैसे v2, v3) भी पुश करेगा
        tags: |
          rahuldockerhub526/rahul-devops-demo:v${{ github.run_number }}
          rahuldockerhub526/rahul-devops-demo:latest